// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type StoredRecord interface {
	IsStoredRecord()
}

type CaseAction struct {
	ID           string  `json:"ID"`
	CreatedAt    *string `json:"CreatedAt"`
	UpdatedAt    *string `json:"UpdatedAt"`
	DeletedAt    *string `json:"DeletedAt"`
	CaseRecordID string  `json:"CaseRecordID"`
	Action       string  `json:"Action"`
}

func (CaseAction) IsStoredRecord() {}

type CaseRecord struct {
	ID        string  `json:"ID"`
	CreatedAt *string `json:"CreatedAt"`
	UpdatedAt *string `json:"UpdatedAt"`
	DeletedAt *string `json:"DeletedAt"`
	Status    string  `json:"Status"`
}

func (CaseRecord) IsStoredRecord() {}
