// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type StoredRecord interface {
	IsStoredRecord()
	GetID() string
	GetCreatedAt() *string
	GetUpdatedAt() *string
	GetDeletedAt() *string
}

type CaseAction struct {
	ID           string  `json:"ID"`
	CreatedAt    *string `json:"CreatedAt"`
	UpdatedAt    *string `json:"UpdatedAt"`
	DeletedAt    *string `json:"DeletedAt"`
	CaseRecordID string  `json:"CaseRecordID"`
	Action       string  `json:"Action"`
}

func (CaseAction) IsStoredRecord()            {}
func (this CaseAction) GetID() string         { return this.ID }
func (this CaseAction) GetCreatedAt() *string { return this.CreatedAt }
func (this CaseAction) GetUpdatedAt() *string { return this.UpdatedAt }
func (this CaseAction) GetDeletedAt() *string { return this.DeletedAt }

type CaseRecord struct {
	ID        string  `json:"ID"`
	CreatedAt *string `json:"CreatedAt"`
	UpdatedAt *string `json:"UpdatedAt"`
	DeletedAt *string `json:"DeletedAt"`
	Status    string  `json:"Status"`
}

func (CaseRecord) IsStoredRecord()            {}
func (this CaseRecord) GetID() string         { return this.ID }
func (this CaseRecord) GetCreatedAt() *string { return this.CreatedAt }
func (this CaseRecord) GetUpdatedAt() *string { return this.UpdatedAt }
func (this CaseRecord) GetDeletedAt() *string { return this.DeletedAt }
