// Code generated by go-swagger; DO NOT EDIT.

package ops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	"github.com/case-management-suite/models"
)

// ExecuteActionOKCode is the HTTP code returned for type ExecuteActionOK
const ExecuteActionOKCode int = 200

/*
ExecuteActionOK UUIDResponse

swagger:response executeActionOK
*/
type ExecuteActionOK struct {

	/*
	  In: Body
	*/
	Payload models.UUIDResponse `json:"body,omitempty"`
}

// NewExecuteActionOK creates ExecuteActionOK with default headers values
func NewExecuteActionOK() *ExecuteActionOK {

	return &ExecuteActionOK{}
}

// WithPayload adds the payload to the execute action o k response
func (o *ExecuteActionOK) WithPayload(payload models.UUIDResponse) *ExecuteActionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the execute action o k response
func (o *ExecuteActionOK) SetPayload(payload models.UUIDResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ExecuteActionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*
ExecuteActionDefault execute action default

swagger:response executeActionDefault
*/
type ExecuteActionDefault struct {
	_statusCode int
	/*

	 */
	Code int16 `json:"Code"`
	/*

	 */
	Message string `json:"Message"`
}

// NewExecuteActionDefault creates ExecuteActionDefault with default headers values
func NewExecuteActionDefault(code int) *ExecuteActionDefault {
	if code <= 0 {
		code = 500
	}

	return &ExecuteActionDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the execute action default response
func (o *ExecuteActionDefault) WithStatusCode(code int) *ExecuteActionDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the execute action default response
func (o *ExecuteActionDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithCode adds the code to the execute action default response
func (o *ExecuteActionDefault) WithCode(code int16) *ExecuteActionDefault {
	o.Code = code
	return o
}

// SetCode sets the code to the execute action default response
func (o *ExecuteActionDefault) SetCode(code int16) {
	o.Code = code
}

// WithMessage adds the message to the execute action default response
func (o *ExecuteActionDefault) WithMessage(message string) *ExecuteActionDefault {
	o.Message = message
	return o
}

// SetMessage sets the message to the execute action default response
func (o *ExecuteActionDefault) SetMessage(message string) {
	o.Message = message
}

// WriteResponse to the client
func (o *ExecuteActionDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Code

	code := swag.FormatInt16(o.Code)
	if code != "" {
		rw.Header().Set("Code", code)
	}

	// response header Message

	message := o.Message
	if message != "" {
		rw.Header().Set("Message", message)
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
