// Code generated by go-swagger; DO NOT EDIT.

package ops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// FindCasesHandlerFunc turns a function with the right signature into a find cases handler
type FindCasesHandlerFunc func(FindCasesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FindCasesHandlerFunc) Handle(params FindCasesParams) middleware.Responder {
	return fn(params)
}

// FindCasesHandler interface for that can handle valid find cases params
type FindCasesHandler interface {
	Handle(FindCasesParams) middleware.Responder
}

// NewFindCases creates a new http.Handler for the find cases operation
func NewFindCases(ctx *middleware.Context, handler FindCasesHandler) *FindCases {
	return &FindCases{Context: ctx, Handler: handler}
}

/*
	FindCases swagger:route GET /case findCases

# Find all cases for the user

This will show all available cases
*/
type FindCases struct {
	Context *middleware.Context
	Handler FindCasesHandler
}

func (o *FindCases) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewFindCasesParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
