// Code generated by go-swagger; DO NOT EDIT.

package ops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	"github.com/case-management-suite/models"
)

// FindCasesOKCode is the HTTP code returned for type FindCasesOK
const FindCasesOKCode int = 200

/*
FindCasesOK CaseRecord

swagger:response findCasesOK
*/
type FindCasesOK struct {

	/*
	  In: Body
	*/
	Payload []models.CaseRecord `json:"body,omitempty"`
}

// NewFindCasesOK creates FindCasesOK with default headers values
func NewFindCasesOK() *FindCasesOK {

	return &FindCasesOK{}
}

// WithPayload adds the payload to the find cases o k response
func (o *FindCasesOK) WithPayload(payload []models.CaseRecord) *FindCasesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find cases o k response
func (o *FindCasesOK) SetPayload(payload []models.CaseRecord) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindCasesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]models.CaseRecord, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*
FindCasesDefault find cases default

swagger:response findCasesDefault
*/
type FindCasesDefault struct {
	_statusCode int
	/*

	 */
	Code int16 `json:"Code"`
	/*

	 */
	Message string `json:"Message"`
}

// NewFindCasesDefault creates FindCasesDefault with default headers values
func NewFindCasesDefault(code int) *FindCasesDefault {
	if code <= 0 {
		code = 500
	}

	return &FindCasesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the find cases default response
func (o *FindCasesDefault) WithStatusCode(code int) *FindCasesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the find cases default response
func (o *FindCasesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithCode adds the code to the find cases default response
func (o *FindCasesDefault) WithCode(code int16) *FindCasesDefault {
	o.Code = code
	return o
}

// SetCode sets the code to the find cases default response
func (o *FindCasesDefault) SetCode(code int16) {
	o.Code = code
}

// WithMessage adds the message to the find cases default response
func (o *FindCasesDefault) WithMessage(message string) *FindCasesDefault {
	o.Message = message
	return o
}

// SetMessage sets the message to the find cases default response
func (o *FindCasesDefault) SetMessage(message string) {
	o.Message = message
}

// WriteResponse to the client
func (o *FindCasesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Code

	code := swag.FormatInt16(o.Code)
	if code != "" {
		rw.Header().Set("Code", code)
	}

	// response header Message

	message := o.Message
	if message != "" {
		rw.Header().Set("Message", message)
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
