// Code generated by go-swagger; DO NOT EDIT.

package ops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// FindCaseHandlerFunc turns a function with the right signature into a find case handler
type FindCaseHandlerFunc func(FindCaseParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FindCaseHandlerFunc) Handle(params FindCaseParams) middleware.Responder {
	return fn(params)
}

// FindCaseHandler interface for that can handle valid find case params
type FindCaseHandler interface {
	Handle(FindCaseParams) middleware.Responder
}

// NewFindCase creates a new http.Handler for the find case operation
func NewFindCase(ctx *middleware.Context, handler FindCaseHandler) *FindCase {
	return &FindCase{Context: ctx, Handler: handler}
}

/*
	FindCase swagger:route GET /case/{id} findCase

# Find a given case

This will show the requested case
*/
type FindCase struct {
	Context *middleware.Context
	Handler FindCaseHandler
}

func (o *FindCase) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewFindCaseParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
