// Code generated by go-swagger; DO NOT EDIT.

package ops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	"github.com/case-management-suite/models"
)

// FindCaseOKCode is the HTTP code returned for type FindCaseOK
const FindCaseOKCode int = 200

/*
FindCaseOK CaseRecord

swagger:response findCaseOK
*/
type FindCaseOK struct {

	/*
	  In: Body
	*/
	Payload models.CaseRecord `json:"body,omitempty"`
}

// NewFindCaseOK creates FindCaseOK with default headers values
func NewFindCaseOK() *FindCaseOK {

	return &FindCaseOK{}
}

// WithPayload adds the payload to the find case o k response
func (o *FindCaseOK) WithPayload(payload models.CaseRecord) *FindCaseOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find case o k response
func (o *FindCaseOK) SetPayload(payload models.CaseRecord) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindCaseOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*
FindCaseDefault find case default

swagger:response findCaseDefault
*/
type FindCaseDefault struct {
	_statusCode int
	/*

	 */
	Code int16 `json:"Code"`
	/*

	 */
	Message string `json:"Message"`
}

// NewFindCaseDefault creates FindCaseDefault with default headers values
func NewFindCaseDefault(code int) *FindCaseDefault {
	if code <= 0 {
		code = 500
	}

	return &FindCaseDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the find case default response
func (o *FindCaseDefault) WithStatusCode(code int) *FindCaseDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the find case default response
func (o *FindCaseDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithCode adds the code to the find case default response
func (o *FindCaseDefault) WithCode(code int16) *FindCaseDefault {
	o.Code = code
	return o
}

// SetCode sets the code to the find case default response
func (o *FindCaseDefault) SetCode(code int16) {
	o.Code = code
}

// WithMessage adds the message to the find case default response
func (o *FindCaseDefault) WithMessage(message string) *FindCaseDefault {
	o.Message = message
	return o
}

// SetMessage sets the message to the find case default response
func (o *FindCaseDefault) SetMessage(message string) {
	o.Message = message
}

// WriteResponse to the client
func (o *FindCaseDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Code

	code := swag.FormatInt16(o.Code)
	if code != "" {
		rw.Header().Set("Code", code)
	}

	// response header Message

	message := o.Message
	if message != "" {
		rw.Header().Set("Message", message)
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
